INSERT INTO MEMBER(ID, PW, NICK, PHONE, ADDR)
VALUES('admin', '1234', '관리자', '010-1111-2222', '순천');

COMMIT;

DELETE FROM MEMBER;

SELECT * FROM MEMBER;

SELECT * FROM li_info;

SELECT * FROM pay_info;

SELECT * FROM plan_info;